package com.buddy.aios.core.ai.response

import com.buddy.aios.core.ai.voice.VoiceResponseProcessor
import com.buddy.aios.core.ai.voice.VoiceResponseProcessorInput
import com.buddy.aios.core.common.logging.AppLogger
import com.buddy.aios.core.domain.entity.BuddyMode
import com.buddy.aios.core.domain.entity.PrivacyLevel
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AIOS Response Composer.
 *
 * Sits between the streaming pipeline and the UI/TTS/Island layers.
 * Receives the COMPLETE AI response and fans it out into separate response channels:
 *
 * ```
 * Full AI Response
 *      ↓
 * ResponseComposer
 * ├── screenText      → full, unchanged AI text → chat bubbles (handled upstream)
 * ├── voiceText       → natural spoken summary  → TextToSpeechManager
 * └── (notification)  → handled by AIOSIslandStateManager via ChatViewModel
 * ```
 *
 * ResponseComposer is responsible ONLY for generating the voice response.
 * The Dynamic Island notification is driven by ChatViewModel directly
 * using metadata from the Message.
 *
 * Rules:
 * - screenText is NEVER modified — the full response is always shown on screen.
 * - voiceText is generated by [VoiceResponseProcessor] which handles all response
 *   classifications: SHORT_CONVERSATION, TOOL_CONFIRMATION, CODE_EXPLANATION, LONG_INFORMATION.
 * - Voice is NOT a truncated version of the screen text — it is a natural explanation.
 */
@Singleton
class ResponseComposer @Inject constructor(
    private val voiceResponseProcessor: VoiceResponseProcessor,
) {
    companion object {
        private const val TAG = "ResponseComposer"
    }

    /**
     * Composes the voice response channel for a complete AI response.
     *
     * @param userMessage   The original user message (for context-aware voice generation).
     * @param fullResponse  The complete, final AI response text (the screen version).
     * @param toolLabel     Human-readable tool confirmation string, if a tool was executed.
     * @param buddyMode     Current BuddyMode (SILENT/OFF suppress voice).
     * @param privacyLevel  Current privacy level (passed to voice processor).
     * @return [ComposedResponse] with the voice text ready for TTS.
     */
    suspend fun compose(
        userMessage: String,
        fullResponse: String,
        toolLabel: String? = null,
        buddyMode: BuddyMode = BuddyMode.ACTIVE,
        privacyLevel: PrivacyLevel = PrivacyLevel.LOCAL_ONLY,
    ): ComposedResponse {
        AppLogger.d(TAG, "Composing voice response: responseLength=${fullResponse.length}, tool=$toolLabel")

        // Voice Response — delegate fully to VoiceResponseProcessor
        // It understands SHORT_CONVERSATION, CODE, LONG_INFORMATION, TOOL_CONFIRMATION, ERROR
        val spokenResponse = voiceResponseProcessor.process(
            VoiceResponseProcessorInput(
                userMessage = userMessage,
                fullResponse = fullResponse,
                toolResultText = toolLabel,
                buddyMode = buddyMode,
                privacyLevel = privacyLevel,
            )
        )

        AppLogger.d(TAG, "Voice composed: '${spokenResponse.text.take(80)}' (summarized=${spokenResponse.isSummarized})")

        return ComposedResponse(
            screenText = fullResponse,
            voiceText = spokenResponse.text,
        )
    }
}

/**
 * The composed response containing all output channels.
 *
 * @param screenText  Full AI response — shown in chat bubbles unchanged (informational).
 * @param voiceText   Natural spoken explanation — spoken by TTS.
 */
data class ComposedResponse(
    val screenText: String,
    val voiceText: String,
)
