package com.buddy.aios.core.ai.brain

/**
 * Stage 8 Expanded User Intent Classification.
 */
enum class UserIntent {
    QUESTION,
    TASK_CREATE,
    TASK_COMPLETE,
    TASK_DELETE,
    REMINDER_CREATE,
    REMINDER_MODIFY,
    REMINDER_DELETE,
    REMINDER_QUERY,
    MEMORY_SAVE,
    MEMORY_QUERY,
    EXPLANATION,
    SUMMARY,
    PLANNING,
    RECOMMENDATION,
    STATUS,
    MORNING_BRIEFING,
    TRAVEL,
    CODING,
    CASUAL_CONVERSATION,
    DEVICE_ACTION,
    MODE_CHANGE,
    PERSONAL_ADVICE,
    PRIORITY_REQUEST,
    SCHEDULE_PLANNING,
    DAILY_PLAN,
    CONTEXT_QUERY,
    WHAT_SHOULD_I_DO_NOW,
    WHAT_IS_IMPORTANT_TODAY,
    EXPLANATION_WHY,
    GENERAL_QUERY,
}
